#!/bin/bash

# مسیر مورد نظر شما
CERTS_DIR="/var/lib/marznode/certs"

# اگر پوشه وجود نداشته باشد، آن را می‌سازد (-p یعنی اگر والد هم نبود بساز)
if [ ! -d "$CERTS_DIR" ]; then
    echo "Directory $CERTS_DIR does not exist. Creating it..."
    mkdir -p "$CERTS_DIR"
fi

echo "Writing certificate files..."

# ایجاد یا بازنویسی فایل fullchain.pem
cat > "$CERTS_DIR/fullchain.pem" << 'EOF'
-----BEGIN CERTIFICATE-----
MIIDrDCCAzOgAwIBAgISBtqXlCLgsEDphKJJ0npYW60PMAoGCCqGSM49BAMDMDIx
CzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQDEwJF
NzAeFw0yNjAyMDcwODQ2MTVaFw0yNjA1MDgwODQ2MTRaMBcxFTATBgNVBAMTDG1o
dWJiLW1jYy5pcjBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABO+IyxbyDkebJVwV
Ge5xd2bM7H2KZdKKqkuuZbPsbbhs4Q5TDNuFvun3MSIC4QqOkLLI6Ui1yGfNC8H+
fSmQPw2jggJCMIICPjAOBgNVHQ8BAf8EBAMCB4AwHQYDVR0lBBYwFAYIKwYBBQUH
AwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFKi4M7zUWrwFruJO
G/wRaC1URhd2MB8GA1UdIwQYMBaAFK5IntyHHUSgb9qi5WB0BHjCnACAMDIGCCsG
AQUFBwEBBCYwJDAiBggrBgEFBQcwAoYWaHR0cDovL2U3LmkubGVuY3Iub3JnLzA/
BgNVHREEODA2gg4qLm1odWJiLW1jYy5pcoILKi5taXplMzYuaXKCDG1odWJiLW1j
Yy5pcoIJbWl6ZTM2LmlyMBMGA1UdIAQMMAowCAYGZ4EMAQIBMC0GA1UdHwQmMCQw
IqAgoB6GHGh0dHA6Ly9lNy5jLmxlbmNyLm9yZy8xNi5jcmwwggEEBgorBgEEAdZ5
AgQCBIH1BIHyAPAAdgCWl2S/VViXrfdDh2g3CEJ36fA61fak8zZuRqQ/D8qpxgAA
AZw3fVN8AAAEAwBHMEUCIGz+FjG+B3vWi0ABMqDTe2Zn/8qy+wuAcvH5r7tqL9CE
AiEA359oSlhKXqyp0ge3FwHFKjhktAjBLGBTZAlzyDKwHXQAdgDRbqmlaAd+ZjWg
Pzel3bwDpTxBEhTUiBj16TGzI8uVBAAAAZw3fVQIAAAEAwBHMEUCIQDaJz31jWwZ
s+u4/taOjTqIlUGmsGr/nt0k+aBWa1atPgIgBkDBHLnjm6BIpTiddyC2g90Vdd/R
qRkNJzTiPRh/rEYwCgYIKoZIzj0EAwMDZwAwZAIwR2lI9Q9Dh1jZ6kszQ1H2qt50
e8FfbT/0FGbpl9P0lQq4ziC/qwEHH665lvFP3oPvAjASK7V6Xj2YBa0PIThHaPHt
PPVlkzlUwYVkr029vXo8Co2M/mu3pd+F9nSBdwwKfmg=
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
MIIEVzCCAj+gAwIBAgIRAKp18eYrjwoiCWbTi7/UuqEwDQYJKoZIhvcNAQELBQAw
TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjQwMzEzMDAwMDAw
WhcNMjcwMzEyMjM1OTU5WjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
RW5jcnlwdDELMAkGA1UEAxMCRTcwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAARB6AST
CFh/vjcwDMCgQer+VtqEkz7JANurZxLP+U9TCeioL6sp5Z8VRvRbYk4P1INBmbef
QHJFHCxcSjKmwtvGBWpl/9ra8HW0QDsUaJW2qOJqceJ0ZVFT3hbUHifBM/2jgfgw
gfUwDgYDVR0PAQH/BAQDAgGGMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcD
ATASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBSuSJ7chx1EoG/aouVgdAR4
wpwAgDAfBgNVHSMEGDAWgBR5tFnme7bl5AFzgAiIyBpY9umbbjAyBggrBgEFBQcB
AQQmMCQwIgYIKwYBBQUHMAKGFmh0dHA6Ly94MS5pLmxlbmNyLm9yZy8wEwYDVR0g
BAwwCjAIBgZngQwBAgEwJwYDVR0fBCAwHjAcoBqgGIYWaHR0cDovL3gxLmMubGVu
Y3Iub3JnLzANBgkqhkiG9w0BAQsFAAOCAgEAjx66fDdLk5ywFn3CzA1w1qfylHUD
aEf0QZpXcJseddJGSfbUUOvbNR9N/QQ16K1lXl4VFyhmGXDT5Kdfcr0RvIIVrNxF
h4lqHtRRCP6RBRstqbZ2zURgqakn/Xip0iaQL0IdfHBZr396FgknniRYFckKORPG
yM3QKnd66gtMst8I5nkRQlAg/Jb+Gc3egIvuGKWboE1G89NTsN9LTDD3PLj0dUMr
OIuqVjLB8pEC6yk9enrlrqjXQgkLEYhXzq7dLafv5Vkig6Gl0nuuqjqfp0Q1bi1o
yVNAlXe6aUXw92CcghC9bNsKEO1+M52YY5+ofIXlS/SEQbvVYYBLZ5yeiglV6t3S
M6H+vTG0aP9YHzLn/KVOHzGQfXDP7qM5tkf+7diZe7o2fw6O7IvN6fsQXEQQj8TJ
UXJxv2/uJhcuy/tSDgXwHM8Uk34WNbRT7zGTGkQRX0gsbjAea/jYAoWv0ZvQRwpq
Pe79D/i7Cep8qWnA+7AE/3B3S/3dEEYmc0lpe1366A/6GEgk3ktr9PEoQrLChs6I
tu3wnNLB2euC8IKGLQFpGtOO/2/hiAKjyajaBP25w1jF0Wl8Bbqne3uZ2q1GyPFJ
YRmT7/OXpmOH/FVLtwS+8ng1cAmpCujPwteJZNcDG0sF2n/sc0+SQf49fdyUK0ty
+VUwFj9tmWxyR/M=
-----END CERTIFICATE-----

EOF

# ایجاد یا بازنویسی فایل key.pem
cat > "$CERTS_DIR/key.pem" << 'EOF'
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIN4l/GGPELSH2zey9lzvmpZkv6BC6oDZYwuWf/OLn+xmoAoGCCqGSM49
AwEHoUQDQgAE74jLFvIOR5slXBUZ7nF3ZszsfYpl0oqqS65ls+xtuGzhDlMM24W+
6fcxIgLhCo6QssjpSLXIZ80Lwf59KZA/DQ==
-----END EC PRIVATE KEY-----

EOF

# ایمن‌سازی دسترسی‌ها
chmod 600 "$CERTS_DIR/key.pem"
chmod 644 "$CERTS_DIR/fullchain.pem"

echo "All done! Certificates are placed in $CERTS_DIR"
