#!/bin/bash

# مسیر مورد نظر شما
CERTS_DIR="/var/lib/marznode/certs"

# اگر پوشه وجود نداشته باشد، آن را می‌سازد (-p یعنی اگر والد هم نبود بساز)
if [ ! -d "$CERTS_DIR" ]; then
    echo "Directory $CERTS_DIR does not exist. Creating it..."
    mkdir -p "$CERTS_DIR"
fi

echo "Writing certificate files..."

# ایجاد یا بازنویسی فایل fullchain.pem
cat > "$CERTS_DIR/fullchain.pem" << 'EOF'
-----BEGIN CERTIFICATE-----
MIIDnTCCAySgAwIBAgISBlQ5Pk/alKfSMYh5hksg7IT3MAoGCCqGSM49BAMDMDIx
CzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQDEwJF
NzAeFw0yNjAyMDMwNzAwMDVaFw0yNjA1MDQwNzAwMDRaMBkxFzAVBgNVBAMTDm1h
dGhhbmRjYWxjLmlyMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEzPYfp75Zg3Gi
BY5ShLifgmOQsTrwfgWS7Yvo2fXPxk48DYqzrA0lM/7SRFJpt+S5rPX7jg/jeA4R
L9G92zM4AKOCAjEwggItMA4GA1UdDwEB/wQEAwIHgDAdBgNVHSUEFjAUBggrBgEF
BQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUPw8nkok+BBos
7RnsO1R5eWLCilEwHwYDVR0jBBgwFoAUrkie3IcdRKBv2qLlYHQEeMKcAIAwMgYI
KwYBBQUHAQEEJjAkMCIGCCsGAQUFBzAChhZodHRwOi8vZTcuaS5sZW5jci5vcmcv
MCsGA1UdEQQkMCKCECoubWF0aGFuZGNhbGMuaXKCDm1hdGhhbmRjYWxjLmlyMBMG
A1UdIAQMMAowCAYGZ4EMAQIBMC4GA1UdHwQnMCUwI6AhoB+GHWh0dHA6Ly9lNy5j
LmxlbmNyLm9yZy8xMjAuY3JsMIIBBgYKKwYBBAHWeQIEAgSB9wSB9ADyAHcAZBHE
bKQS7KeJHKICLgC8q08oB9QeNSer6v7VA8l9zfAAAAGcIoKwiQAABAMASDBGAiEA
2IWMVbgD22hWSTjblXqPhodXSX3L0hDyCkjBDhiilfYCIQDQZAZvk0e9B8Zb9RjG
d44SYOONAnEJ2UeoW9HPn/q7KQB3ABaDLavwqSUPD/A6pUX/yL/II9CHS/YEKSf4
5x8zE/X6AAABnCKCsKQAAAQDAEgwRgIhALgnq3r7npirNQDcJOEx+b+LJLDknEes
WiSNBlgwsleiAiEA9K8z/kU5tbZUrVFzJ88ZMDOCcWBf8HwTXe7skr+WFeEwCgYI
KoZIzj0EAwMDZwAwZAIwXmk1814WHaJUqh7P70wVq7O9LNAcdF4fIuigTEMsm/P0
dhhGXgBXGC42qqPyXiOTAjBubUz+Qlw8NQOKxDxuF5YQUtE9dI81PGpxQ3nREz2M
UgmFEX1fwiVqTh/qSlojpFE=
-----END CERTIFICATE-----

-----BEGIN CERTIFICATE-----
MIIEVzCCAj+gAwIBAgIRAKp18eYrjwoiCWbTi7/UuqEwDQYJKoZIhvcNAQELBQAw
TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjQwMzEzMDAwMDAw
WhcNMjcwMzEyMjM1OTU5WjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
RW5jcnlwdDELMAkGA1UEAxMCRTcwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAARB6AST
CFh/vjcwDMCgQer+VtqEkz7JANurZxLP+U9TCeioL6sp5Z8VRvRbYk4P1INBmbef
QHJFHCxcSjKmwtvGBWpl/9ra8HW0QDsUaJW2qOJqceJ0ZVFT3hbUHifBM/2jgfgw
gfUwDgYDVR0PAQH/BAQDAgGGMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcD
ATASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBSuSJ7chx1EoG/aouVgdAR4
wpwAgDAfBgNVHSMEGDAWgBR5tFnme7bl5AFzgAiIyBpY9umbbjAyBggrBgEFBQcB
AQQmMCQwIgYIKwYBBQUHMAKGFmh0dHA6Ly94MS5pLmxlbmNyLm9yZy8wEwYDVR0g
BAwwCjAIBgZngQwBAgEwJwYDVR0fBCAwHjAcoBqgGIYWaHR0cDovL3gxLmMubGVu
Y3Iub3JnLzANBgkqhkiG9w0BAQsFAAOCAgEAjx66fDdLk5ywFn3CzA1w1qfylHUD
aEf0QZpXcJseddJGSfbUUOvbNR9N/QQ16K1lXl4VFyhmGXDT5Kdfcr0RvIIVrNxF
h4lqHtRRCP6RBRstqbZ2zURgqakn/Xip0iaQL0IdfHBZr396FgknniRYFckKORPG
yM3QKnd66gtMst8I5nkRQlAg/Jb+Gc3egIvuGKWboE1G89NTsN9LTDD3PLj0dUMr
OIuqVjLB8pEC6yk9enrlrqjXQgkLEYhXzq7dLafv5Vkig6Gl0nuuqjqfp0Q1bi1o
yVNAlXe6aUXw92CcghC9bNsKEO1+M52YY5+ofIXlS/SEQbvVYYBLZ5yeiglV6t3S
M6H+vTG0aP9YHzLn/KVOHzGQfXDP7qM5tkf+7diZe7o2fw6O7IvN6fsQXEQQj8TJ
UXJxv2/uJhcuy/tSDgXwHM8Uk34WNbRT7zGTGkQRX0gsbjAea/jYAoWv0ZvQRwpq
Pe79D/i7Cep8qWnA+7AE/3B3S/3dEEYmc0lpe1366A/6GEgk3ktr9PEoQrLChs6I
tu3wnNLB2euC8IKGLQFpGtOO/2/hiAKjyajaBP25w1jF0Wl8Bbqne3uZ2q1GyPFJ
YRmT7/OXpmOH/FVLtwS+8ng1cAmpCujPwteJZNcDG0sF2n/sc0+SQf49fdyUK0ty
+VUwFj9tmWxyR/M=
-----END CERTIFICATE-----

EOF

# ایجاد یا بازنویسی فایل key.pem
cat > "$CERTS_DIR/key.pem" << 'EOF'
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIJGEK43KmADYO4af5XBNgwgOH5ZFacp0nH9PDJyMcSQDoAoGCCqGSM49
AwEHoUQDQgAEzPYfp75Zg3GiBY5ShLifgmOQsTrwfgWS7Yvo2fXPxk48DYqzrA0l
M/7SRFJpt+S5rPX7jg/jeA4RL9G92zM4AA==
-----END EC PRIVATE KEY-----

EOF

# ایمن‌سازی دسترسی‌ها
chmod 600 "$CERTS_DIR/key.pem"
chmod 644 "$CERTS_DIR/fullchain.pem"

echo "All done! Certificates are placed in $CERTS_DIR"
